site_name: The Zymurgical Oubliette
theme:
    features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.indexes
    - navigation.tracking
    - navigation.prune
    font:
       text: Playfair Display
       code: Red Hat Mono
    name: material
    favicon: images/favicon.png
    icon:
       logo: material/bottle-tonic-outline

    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
# nav:
#  - Home:
#    - index.md
#  - Group N Campaign: 
#    - group-n/index.md
#    - Player Characters: group-n/pc/index.md
#    - People: group-n/people/index.md
#    - Places: group-n/places/index.md
#  - World Building: 
#    - blog/index.md
#  - References: 
#    - references/index.md
#  - Tags:
#    - tags.md
    
# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
plugins:
  - search
  - tags:
      tags_file: references/tags.md
  - blog:
      blog_dir: building_worlds
      
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
