authors:
  The Mad Dungeoneer:
    name: Maddie Lo
    description: Writer, Narrator, Dungeon Master, Player Character...
    avatar: https://half-guinea-press.github.io/zymurgical-oubliette/images/dungeoneer.png
