characterSheet = html.Div(
    [
        dbc.Row(
            [
                dbc.Col(
                    [
                        html.Br(),
                        html.H1("Player Name")
                        html.Br()
                    ]
                ),
                dbc.Col(
                    [
                        dbc.Row(
                            [
                                dbc.Col(html.H3("Class/Level")),
                                dbc.Col(html.H3("Player Name"))
                            ]
                        ),
                        dbc.Row(
                            [
                                dbc.Col(html.H3("Species")),
                                dbc.Col(html.H3("Background")),
                                dbc.Col(html.H3("Experience")),
                            ]
                        )
                    ]
                ),
            ]
        ),
        dbc.Row(
            [
                dbc.Col(
                    [
                        dbc.Col(
                            [
                                dbc.Card(
                                    [
                                        dbc.CardHeader("Strength"),
                                        dbc.CardBody([html.H5("18")]),
                                        dbc.CardFooter([html.P("+4")]),
                                    ]
                                ),
                                dbc.Card(
                                    [
                                        dbc.CardHeader("Dexterity"),
                                        dbc.CardBody([html.H5("18")]),
                                        dbc.CardFooter([html.P("+4")]),
                                    ]
                                ),
                                dbc.Card(
                                    [
                                        dbc.CardHeader("Constitution"),
                                        dbc.CardBody([html.H5("18")]),
                                        dbc.CardFooter([html.P("+4")]),
                                    ]
                                ),
                                dbc.Card(
                                    [
                                        dbc.CardHeader("Inteligence"),
                                        dbc.CardBody([html.H5("18")]),
                                        dbc.CardFooter([html.P("+4")]),
                                    ]
                                ),
                                dbc.Card(
                                    [
                                        dbc.CardHeader("Wisdom"),
                                        dbc.CardBody([html.H5("18")]),
                                        dbc.CardFooter([html.P("+4"))]),
                                    ]
                                ),
                                dbc.Card(
                                    [
                                        dbc.CardHeader("Charisma"),
                                        dbc.CardBody([html.H5("18")]),
                                        dbc.CardFooter([html.P("+4")]),
                                    ]
                                ),
                            ]
                        ),
                        dbc.Col(
                            [
                                dbc.Card(
                                    [
                                        dbc.CardHeader("Saving Throws")
                                        dbc.CardBody(
                                            [
                                                dbc.Row(
                                            ]
                                        )
                                    ]
                                )
                            ]
                        )
                    ]
                ),
                dbc.Col(
                    [
                        
                    ]
                ),
                dbc.Col(
                    [
                        
                    ]
                ),
            ]
        )
    ]
)
